version: "3.9"
services:
  weather_1:
    build: ../../packages/server/
    image: weather
  weather_2:
    image: weather
    depends_on:
      - weather_1
  auth:
    build: ../../packages/auth/
  nginx:
    image: nginx:alpine
    volumes:
      - ../../configs/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - auth
      - weather_1
      - weather_2
