/* this code was generated by automated tool, 
   should not edit by hand */

export interface AuthService {
  Auth(request: RequestAuth): Promise<ResponseAuth>;
}

export interface RequestAuth {
  name?: string;
}

export interface ResponseAuth {
  authenticated?: boolean;
}
