version: "3.9"
services:
  weather:
    build: ./server/
    image: weather
    ports:
      - 80:8888
    depends_on:
      - twemproxy
  r_1:
    image: redis:alpine
  r_1_rep:
    image: redis:alpine
  r_2:
    image: redis:alpine
  r_2_rep:
    image: redis:alpine
  r_1_config:
    image: redis:alpine
    command: "redis-cli -h r_1_rep REPLICAOF r_1 6379"
    depends_on:
      - r_1
      - r_1_rep
  r_2_config:
    image: redis:alpine
    command: "redis-cli -h r_2_rep REPLICAOF r_2 6379"
    depends_on:
      - r_2
      - r_2_rep
  twemproxy:
    image: vimagick/twemproxy
    command: --conf-file=nutcracker.yml
    volumes:
      - ./twemproxy:/opt/twemproxy:ro
    ports:
      - "6379:6379"
      - "22222:22222"
    depends_on:
      - r_1_config
      - r_2_config